import Head from 'next/head'
import Image from 'next/image'
import TestList from '../src/component/TestList'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Axios from 'axios'
import GetEmployeeList from '../src/component/GetEmployeeList'
// import GetEmployeeListWithPaging from '../src/component/GetEmployeeListWithPaging'

export default function Home() {

  // spring boot 로 부터 받은 자원들을 저장할 곳
  const [list, setList] = useState( [] );
  const API_URL = '/data3';

  const [elist, setElist] = useState( [] );
  const EMP_API_URL = '/emp';

  const callDataFromSpring = () => {
    Axios.get( 
      API_URL
    ).then( data => {

      console.log( data );
      setList( data.data.ar );

    });
  }

  const callEmpListFromSpring = () => {
    Axios.get(
      EMP_API_URL
    ).then( data => {
      console.log( data.data );
      setElist( data.data.elist );
    })
  }

  useEffect( () => { 
    callDataFromSpring(); 
  }, [] );

  useEffect( () => {
    callEmpListFromSpring();
  }, [] );


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* 
        Spring boot server 의 경로를 호출하여
        받은 자원들을 표현할 컴포넌트 호출
        
      */}
      <TestList list={list} />
      <GetEmployeeList elist={elist} />
      {/* <GetEmployeeListWithPaging elist={elist} /> */}
    </div>
  )
}
